Setup Pipeline scripts

diff --git a/setup-pipeline b/setup-pipeline
--- a/setup-pipeline
+++ b/setup-pipeline
@@ -7,11 +7,16 @@ PIPELINE_FOLDER=pipeline
 
 usage() {
     echo "$1"
-    echo ${APPNAME}": <stackname> <deployment-S3-bucket-name> <region> <deployment-environment> <key-name>"
-    echo "stackname                 [REQUIRED]: your cloudformation stack name"
-    echo "deployment-S3-bucket-name [REQUIRED]: S3 bucket to store the tempolary template file"
-    echo "deployment-environment    [REQUIRED]: environment where the stack will be deployed. Valid values: Dev|Test|UAT|Prod"
-    echo "region                    [OPTIONAL]: AWS Region where the stack will be deployed"
+    echo ${APPNAME}
+    echo "Environment variables:"
+    echo " STACKNAME                 [REQUIRED]: your cloudformation stack name"
+    echo " S3_BUCKET                 [REQUIRED]: S3 bucket to store the tempolary template file"    
+    echo " TARGET_ENV                [REQUIRED]: environment where the stack will be deployed. Valid values: dev|test|uat|prod"    
+    echo " GIT_CONNECTION_ID         [REQUIRED]: GitHub Connection ID"    
+    echo " BASTION_HOST_KEY_NAME     [REQUIRED]: AWS KeyPair name"
+    echo " REGION                    [OPTIONAL]: AWS Region where the stack will be deployed"
+
+    
 }
 
 MODE=${INFRA_FOLDER}
@@ -22,29 +27,19 @@ if [ ! -d "${FULL_TMP_FOLDER}" ]; then
     mkdir -p ${FULL_TMP_FOLDER}
 fi
 
-if [ ! -z "$1" ]; then
-  STACKNAME=$1
-elif [ -z "${STACKNAME}" ]; then
+if [ -z "${STACKNAME}" ]; then
   usage "Please provide the stackname"
   exit 1
 fi
 
-if [ ! -z "$2" ]; then
-  S3_BUCKET=$2
-elif [ -z "${S3_BUCKET}" ]; then
+if [ -z "${S3_BUCKET}" ]; then
   usage "Please provide the deployment-S3-bucket-name"
   exit 1
 fi
 
-if [ ! -z "$3" ]; then
-  TARGET_ENV=$3
-elif [ -z "${TARGET_ENV}" ]; then
+if [ -z "${TARGET_ENV}" ]; then
   usage "Please provide Target Environment"
   exit 1
-fi
-
-if [ ! -z "$4" ]; then
-  REGION=$4
 fi
 
 AWS_REGION=""
@@ -53,12 +48,23 @@ if [ ! -z "${REGION}" ]; then
   AWS_REGION="--region ${REGION}"
 fi
 
-ROLE_ARN_PARAM=""
+CONNECTION_ID=""
 
-if [ ! -z "$ROLE_ARN" ]; then
-  ROLE_ARN_PARAM="--role-arn ${ROLE_ARN}"
+if [ ! -z "${GIT_CONNECTION_ID}" ]; then
+  CONNECTION_ID="ParameterKey=GitHubConnectionArn,ParameterValue=${GIT_CONNECTION_ID}"
+else
+  usage "Please provide the deployment-S3-bucket-name"
+  exit 1
 fi
 
+BASTION_HOST_KEY_NAME_PARAM=""
+
+if [ -z "${BASTION_HOST_KEY_NAME}" ]; then
+  usage "Please provide AWS BastionHost KeyName"
+  exit 1
+else 
+  BASTION_HOST_KEY_NAME_PARAM="ParameterKey=BastionHostKeyName,ParameterValue=${BASTION_HOST_KEY_NAME}"
+fi
 
 aws cloudformation package --template-file ${MODE}/main-stack.yaml --s3-bucket ${S3_BUCKET} --region ${REGION} --output-template-file ./${FULL_TMP_FOLDER}/main-stack.yaml
 
@@ -71,7 +77,7 @@ if [ "$RET" = "0" ]; then
   --template-body file://${FULL_TMP_FOLDER}/main-stack.yaml \
   --stack-name ${STACKNAME} \
   --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM  CAPABILITY_AUTO_EXPAND  \
-  --parameters  ParameterKey=Environment,ParameterValue=${TARGET_ENV} ParameterKey=BastionHostKeyName,ParameterValue=${BASTION_HOST_KEY_NAME} ${AWS_REGION} ${ROLE_ARN_PARAM}
+  --parameters  ParameterKey=Environment,ParameterValue=${TARGET_ENV} ${BASTION_HOST_KEY_NAME_PARAM} ${CONNECTION_ID} ${AWS_REGION}
     exit $?
   else
     echo "Create stack ${STACKNAME}"
@@ -79,7 +85,7 @@ if [ "$RET" = "0" ]; then
   --template-body file://${FULL_TMP_FOLDER}/main-stack.yaml \
   --stack-name ${STACKNAME} \
   --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM  CAPABILITY_AUTO_EXPAND  \
-  --parameters  ParameterKey=Environment,ParameterValue=${TARGET_ENV} ParameterKey=BastionHostKeyName,ParameterValue=${BASTION_HOST_KEY_NAME} ${AWS_REGION} ${ROLE_ARN_PARAM}
+  --parameters  ParameterKey=Environment,ParameterValue=${TARGET_ENV} ${BASTION_HOST_KEY_NAME_PARAM} ${CONNECTION_ID} ${AWS_REGION}
     exit $?
   fi
 else
